version: '3'
services:

  api-gateway:
    container_name: 321cqu-api-gateway
    build: .
    ports:
     - "8000:8000"
    restart: always
    volumes:
      - /www/services/api_gateway/logs:/src/logs
      - /www/services/api_gateway/config.cfg:/src/utils/config.cfg
      - /www/services/_321CQU_package/python_package:/_321CQU_package
    environment:
      PYTHONPATH: /_321CQU_package
    networks:
      - persist

networks:
  persist:
    external:
      name: 321cqu